#!/usr/bin/env python3
"""Generate the Traditional Mandarin Rime dictionary used by TypeDuck Mandarin."""

from __future__ import annotations

import argparse
import re
import urllib.request
from pathlib import Path

CEDICT_URL = (
    "https://raw.githubusercontent.com/cschiller/zhongwen/"
    "e6b46b6fc9a05655eefa7fb8e6b12be93e6f1618/data/cedict_ts.u8"
)
SOURCE_LABEL = "CC-CEDICT snapshot mirrored by cschiller/zhongwen, commit e6b46b6 (2026-09-27)"

ENTRY_RE = re.compile(
    r"^(?P<trad>\\S+)\\s+(?P<simp>\\S+)\\s+"
    r"(?:\\[\\[(?P<v2>[^]]+)\\]\\]|\\[(?P<v1>[^]]+)\\])\\s+/"
)
TONE_RE = re.compile(r"[1-5]")
BOUNDARY_RE = re.compile(r"([1-5])(?=[A-Za-züÜ])")
NON_PINYIN_RE = re.compile(r"[^a-zv]+")
CANTONESE_PREFIXES = ("jyut6ping3", "loengfan")


def contains_cjk(text: str) -> bool:
    return any(
        "\\u3400" <= ch <= "\\u9fff"
        or "\\U00020000" <= ch <= "\\U0003134f"
        for ch in text
    )


def normalize_pinyin(raw: str) -> str:
    # V1 has spaces between syllables; V2 commonly joins syllables inside [[...]].
    raw = BOUNDARY_RE.sub(r"\\1 ", raw)
    raw = raw.replace("u:", "v").replace("U:", "v").replace("ü", "v").replace("Ü", "v")
    raw = TONE_RE.sub("", raw).lower()
    raw = NON_PINYIN_RE.sub(" ", raw)
    return " ".join(raw.split())


def parse_entries(text: str) -> list[tuple[str, str]]:
    seen: set[tuple[str, str]] = set()
    entries: list[tuple[str, str]] = []
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        match = ENTRY_RE.match(line)
        if not match:
            continue
        traditional = match.group("trad")
        if not contains_cjk(traditional):
            continue
        pinyin = normalize_pinyin(match.group("v2") or match.group("v1") or "")
        if not pinyin:
            continue
        item = (traditional, pinyin)
        if item not in seen:
            seen.add(item)
            entries.append(item)
    return entries


def download_cedict() -> str:
    request = urllib.request.Request(
        CEDICT_URL,
        headers={"User-Agent": "TypeDuck-Mandarin dictionary builder"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8")


def patch_file(path: Path, replacements: list[tuple[str, str]]) -> None:
    text = path.read_text(encoding="utf-8")
    for old, new in replacements:
        if old not in text:
            raise RuntimeError(f"Expected text not found in {path}: {old!r}")
        text = text.replace(old, new, 1)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "rime_dir",
        nargs="?",
        default="app/src/main/assets/rime",
        type=Path,
    )
    args = parser.parse_args()
    rime_dir: Path = args.rime_dir

    raw = download_cedict()
    entries = parse_entries(raw)
    if len(entries) < 100_000:
        raise RuntimeError(f"Parsed only {len(entries)} entries; refusing to build an incomplete dictionary")

    dictionary = [
        "# Rime dictionary",
        "# encoding: utf-8",
        "#",
        "# Generated by script/build-mandarin-dictionary.py",
        f"# Source: {SOURCE_LABEL}",
        "# Data license: CC BY-SA 4.0 (see MANDARIN_DICTIONARY.md)",
        "",
        "---",
        "name: luna_pinyin",
        'version: "2026.09.27-cedict"',
        "sort: by_weight",
        "...",
        "",
    ]
    dictionary.extend(f"{word}\\t{code}" for word, code in entries)
    (rime_dir / "luna_pinyin.dict.yaml").write_text("\\n".join(dictionary) + "\\n", encoding="utf-8")

    (rime_dir / "default.custom.yaml").write_text(
        """# TypeDuck Mandarin: expose only Traditional Mandarin Pinyin
patch:
  schema_list:
    - schema: luna_pinyin
  menu:
    page_size: 50
""",
        encoding="utf-8",
    )

    patch_file(
        rime_dir / "default.yaml",
        [("  - schema: jyut6ping3", "  - schema: luna_pinyin")],
    )
    patch_file(
        rime_dir / "luna_pinyin.schema.yaml",
        [
            ("  name: 普通話", "  name: 國語拼音（繁體）"),
            ("  enable_sentence: false", "  enable_sentence: true"),
            ("  enable_user_dict: false", "  enable_user_dict: true"),
        ],
    )
    patch_file(
        rime_dir / "trime.yaml",
        [("  locale: zh_HK", "  locale: zh_TW")],
    )

    for path in rime_dir.iterdir():
        if path.is_file() and path.name.startswith(CANTONESE_PREFIXES):
            path.unlink()

    print(f"Generated {len(entries)} Traditional Mandarin entries from {SOURCE_LABEL}")


if __name__ == "__main__":
    main()
