name: commit ci
on:
  push:
  workflow_dispatch:

env:
  CI_NAME: Commit CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        run: |
          echo ${GITHUB_REF#refs/*/}
          echo CI_BRANCH=${GITHUB_REF#refs/*/} >> "$GITHUB_ENV"

      - name: Checkout Rime schema assets
        run: git submodule update --init app/src/main/assets/rime

      - name: Generate Traditional Mandarin dictionary
        run: python3 script/build-mandarin-dictionary.py

      - name: Calculate JNI cache hash
        id: cache-hash
        run: script/cache-hash.sh

      - name: Fetch JNI cache
        uses: actions/cache@v4
        id: jni-cache
        with:
          path: app/prebuilt
          key: jni-debug-${{ steps.cache-hash.outputs.hash }}

      - name: Fetch native submodules
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: git submodule update --init --recursive app/src/main/jni/snappy app/src/main/jni/librime

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        run: |
          yes | sdkmanager --licenses >/dev/null || true
          sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;24.0.8215888" \
            "cmake;3.22.1"

      - name: Spotless code style check
        run: make spotless

      - name: Build debug APKs
        run: make debug

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: cp -R app/build/intermediates/stripped_native_libs/debug/out/lib app/prebuilt

      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: TypeDuck-Mandarin-universal
          path: app/build/outputs/apk/**/*universal-debug.apk
          retention-days: 90

      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: TypeDuck-Mandarin-arm64-v8a
          path: app/build/outputs/apk/**/*arm64-v8a-debug.apk
          retention-days: 90
